@echo off
:: Batch script to pause Windows Update until 2077
:: Run as administrator

echo Setting Windows Update pause until 2077...

powershell -Command "Start-Process powershell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -Command \"$endDate = Get-Date -Year 2077 -Month 12 -Day 31; New-Item -Path \\\"HKLM:\\SOFTWARE\\Microsoft\\WindowsUpdate\\UX\\Settings\\\" -Force | Out-Null; Set-ItemProperty -Path \\\"HKLM:\\SOFTWARE\\Microsoft\\WindowsUpdate\\UX\\Settings\\\" -Name \\\"PauseUpdatesStartTime\\\" -Value (Get-Date).ToString(\\\"yyyy-MM-ddTHH:mm:ssZ\\\") -Type String -Force; Set-ItemProperty -Path \\\"HKLM:\\SOFTWARE\\Microsoft\\WindowsUpdate\\UX\\Settings\\\" -Name \\\"PauseUpdatesExpiryTime\\\" -Value $endDate.ToString(\\\"yyyy-MM-ddTHH:mm:ssZ\\\") -Type String -Force; Set-ItemProperty -Path \\\"HKLM:\\SOFTWARE\\Microsoft\\WindowsUpdate\\UX\\Settings\\\" -Name \\\"AllowMUUpdateService\\\" -Value 0 -Type DWord -Force; Set-ItemProperty -Path \\\"HKLM:\\SOFTWARE\\Microsoft\\WindowsUpdate\\UX\\Settings\\\" -Name \\\"PauseFeatureUpdatesStartTime\\\" -Value (Get-Date).ToString(\\\"yyyy-MM-ddTHH:mm:ssZ\\\") -Type String -Force; Set-ItemProperty -Path \\\"HKLM:\\SOFTWARE\\Microsoft\\WindowsUpdate\\UX\\Settings\\\" -Name \\\"PauseFeatureUpdatesEndTime\\\" -Value $endDate.ToString(\\\"yyyy-MM-ddTHH:mm:ssZ\\\") -Type String -Force; Set-ItemProperty -Path \\\"HKLM:\\SOFTWARE\\Microsoft\\WindowsUpdate\\UX\\Settings\\\" -Name \\\"PauseQualityUpdatesStartTime\\\" -Value (Get-Date).ToString(\\\"yyyy-MM-ddTHH:mm:ssZ\\\") -Type String -Force; Set-ItemProperty -Path \\\"HKLM:\\SOFTWARE\\Microsoft\\WindowsUpdate\\UX\\Settings\\\" -Name \\\"PauseQualityUpdatesEndTime\\\" -Value $endDate.ToString(\\\"yyyy-MM-ddTHH:mm:ssZ\\\") -Type String -Force; Write-Host \\\"Windows Update paused until 2077\\\"\"' -Verb RunAs"

echo Done.
